# -*- coding: utf-8 -*-


class MetadataFields:
    REQUIRED_FIELDS = {
        "file": {
            "normalized": "file",
            "core": "os",
            "label": "File",
            "attribute": "File",
            "description": "Nome do arquivo de imagem. [File]",
        },
        "path": {
            "normalized": "path",
            "core": "os",
            "label": "Path",
            "attribute": "Path",
            "description": "Caminho completo do arquivo de imagem. [Path]",
        },
        "format": {
            "normalized": "format",
            "core": "os",
            "label": "Format",
            "attribute": "FormatMod",
            "description": "Formato e modo de cor da imagem. [FormatMod]",
        },
        "size_mb": {
            "normalized": "size_mb",
            "core": "os",
            "label": "Size MB",
            "attribute": "SizeMB",
            "description": "Tamanho do arquivo em megabytes. [SizeMB]",
        },
        "GPSMapDatum": {
            "normalized": "EXIF:GPSInfo:GPSMapDatum",
            "core": "EXIF",
            "label": "GPS Map Datum",
            "attribute": "GPSDatum",
            "description": "Datum geodesico usado nas coordenadas GPS. [GPSDatum]",
        },
        "Model": {
            "normalized": "EXIF:Model",
            "core": "EXIF",
            "label": "Model",
            "attribute": "Model",
            "description": "Modelo da camera que capturou a imagem. [Model]",
        },
        "Software": {
            "normalized": "EXIF:Software",
            "core": "EXIF",
            "label": "Software",
            "attribute": "Firmware",
            "description": "Software ou firmware gravado no metadado. [Firmware]",
        },
        "XResolution": {
            "normalized": "EXIF:XResolution",
            "core": "EXIF",
            "label": "X Resolution",
            "attribute": "DPIWidth",
            "description": "Resolucao horizontal informada no EXIF (DPI). [DPIWidth]",
        },
        "YResolution": {
            "normalized": "EXIF:YResolution",
            "core": "EXIF",
            "label": "Y Resolution",
            "attribute": "DPIHeight",
            "description": "Resolucao vertical informada no EXIF (DPI). [DPIHeight]",
        },
        "ShutterSpeedValue": {
            "normalized": "EXIF:ShutterSpeedValue",
            "core": "EXIF",
            "label": "Shutter Speed Value",
            "attribute": "ShutterSp",
            "description": "Velocidade do obturador registrada no EXIF. [ShutterSp]",
        },
        "DateTimeOriginal": {
            "normalized": "EXIF:DateTimeOriginal",
            "core": "EXIF",
            "label": "Date Time Original",
            "attribute": "DateTime",
            "description": "Data e hora original da captura. [DateTime]",
        },
        "ApertureValue": {
            "normalized": "EXIF:ApertureValue",
            "core": "EXIF",
            "label": "Aperture Value",
            "attribute": "ApertureV",
            "description": "Valor de abertura usado na captura. [ApertureV]",
        },
        "MaxApertureValue": {
            "normalized": "EXIF:MaxApertureValue",
            "core": "EXIF",
            "label": "Max Aperture Value",
            "attribute": "MaxApertV",
            "description": "Maior abertura disponivel da lente. [MaxApertV]",
        },
        "LightSource": {
            "normalized": "EXIF:LightSource",
            "core": "EXIF",
            "label": "Light Source",
            "attribute": "LightSour",
            "description": "Codigo da fonte de iluminacao da cena. [LightSour]",
        },
        "FocalLength": {
            "normalized": "EXIF:FocalLength",
            "core": "EXIF",
            "label": "Focal Length",
            "attribute": "FocalLeng",
            "description": "Distancia focal da lente em mm. [FocalLeng]",
        },
        "ExifImageWidth": {
            "normalized": "EXIF:ExifImageWidth",
            "core": "EXIF",
            "label": "EXIF Image Width",
            "attribute": "WidthPX",
            "description": "Largura da imagem em pixels (EXIF). [WidthPX]",
        },
        "ExifImageHeight": {
            "normalized": "EXIF:ExifImageHeight",
            "core": "EXIF",
            "label": "EXIF Image Height",
            "attribute": "HeightPX",
            "description": "Altura da imagem em pixels (EXIF). [HeightPX]",
        },
        "ExposureTime": {
            "normalized": "EXIF:ExposureTime",
            "core": "EXIF",
            "label": "Exposure Time",
            "attribute": "ExpTime",
            "description": "Tempo de exposicao da foto em segundos. [ExpTime]",
        },
        "FNumber": {
            "normalized": "EXIF:FNumber",
            "core": "EXIF",
            "label": "F Number",
            "attribute": "FNumber",
            "description": "Numero f usado na captura. [FNumber]",
        },
        "ExposureProgram": {
            "normalized": "EXIF:ExposureProgram",
            "core": "EXIF",
            "label": "Exposure Program",
            "attribute": "ExpProg",
            "description": "Programa de exposicao selecionado pela camera. [ExpProg]",
        },
        "ISOSpeedRatings": {
            "normalized": "EXIF:ISOSpeedRatings",
            "core": "EXIF",
            "label": "ISO Speed Ratings",
            "attribute": "ISOSpeed",
            "description": "Sensibilidade ISO usada na captura. [ISOSpeed]",
        },
        "ExposureMode": {
            "normalized": "EXIF:ExposureMode",
            "core": "EXIF",
            "label": "Exposure Mode",
            "attribute": "ExpMode",
            "description": "Modo de exposicao configurado na camera. [ExpMode]",
        },
        "LensSpecification": {
            "normalized": "EXIF:LensSpecification",
            "core": "EXIF",
            "label": "Lens Specification",
            "attribute": "Lens",
            "description": "Faixa focal e de abertura da lente. [Lens]",
        },
        "DigitalZoomRatio": {
            "normalized": "EXIF:DigitalZoomRatio",
            "core": "EXIF",
            "label": "Digital Zoom Ratio",
            "attribute": "ZoomRatio",
            "description": "Razao de zoom digital aplicada na captura. [ZoomRatio]",
        },
        "GpsStatus": {
            "normalized": "EXIF:GPSInfo:GPSStatus",
            "core": "xmp_bloco_1",
            "label": "GPS Status",
            "attribute": "GpsStatus",
            "description": "Status do GPS no momento da foto. [GpsStatus]",
        },
        "AltitudeType": {
            "normalized": "xmp_bloco_1:drone-dji:AltitudeType",
            "core": "xmp_bloco_1",
            "label": "Altitude Type",
            "attribute": "Ytype",
            "description": "Tipo de altitude registrado pelo drone. [Ytype]",
        },
        "GpsLatitude": {
            "normalized": "EXIF:GPSInfo:GPSLatitude",
            "core": "xmp_bloco_1",
            "label": "GPS Latitude",
            "attribute": "GpsLat",
            "description": "Latitude GPS da aeronave na captura. [GpsLat]",
        },
        "GpsLongitude": {
            "normalized": "EXIF:GPSInfo:GPSLongitude",
            "core": "xmp_bloco_1",
            "label": "GPS Longitude",
            "attribute": "GPSLong",
            "description": "Longitude GPS da aeronave na captura. [GPSLong]",
        },
        "AbsoluteAltitude": {
            "normalized": "xmp_bloco_1:drone-dji:AbsoluteAltitude",
            "core": "xmp_bloco_1",
            "label": "Absolute Altitude",
            "attribute": "AbsY",
            "description": "Altitude absoluta da aeronave. [AbsY]",
        },
        "RelativeAltitude": {
            "normalized": "xmp_bloco_1:drone-dji:RelativeAltitude",
            "core": "xmp_bloco_1",
            "label": "Relative Altitude",
            "attribute": "RelativeY",
            "description": "Altitude relativa ao ponto de decolagem. [RelativeY]",
        },
        "GimbalRollDegree": {
            "normalized": "xmp_bloco_1:drone-dji:GimbalRollDegree",
            "core": "xmp_bloco_1",
            "label": "Gimbal Roll Degree",
            "attribute": "GimbRoll",
            "description": "Angulo de rolagem do gimbal em graus. [GimbRoll]",
        },
        "GimbalYawDegree": {
            "normalized": "xmp_bloco_1:drone-dji:GimbalYawDegree",
            "core": "xmp_bloco_1",
            "label": "Gimbal Yaw Degree",
            "attribute": "GimbYaw",
            "description": "Angulo de yaw do gimbal em graus. [GimbYaw]",
        },
        "GimbalPitchDegree": {
            "normalized": "xmp_bloco_1:drone-dji:GimbalPitchDegree",
            "core": "xmp_bloco_1",
            "label": "Gimbal Pitch Degree",
            "attribute": "GimbPitch",
            "description": "Angulo de pitch do gimbal em graus. [GimbPitch]",
        },
        "FlightRollDegree": {
            "normalized": "xmp_bloco_1:drone-dji:FlightRollDegree",
            "core": "xmp_bloco_1",
            "label": "Flight Roll Degree",
            "attribute": "DroneRoll",
            "description": "Angulo de rolagem da aeronave em graus. [DroneRoll]",
        },
        "FlightYawDegree": {
            "normalized": "xmp_bloco_1:drone-dji:FlightYawDegree",
            "core": "xmp_bloco_1",
            "label": "Flight Yaw Degree",
            "attribute": "DroneYaw",
            "description": "Angulo de yaw da aeronave em graus. [DroneYaw]",
        },
        "FlightPitchDegree": {
            "normalized": "xmp_bloco_1:drone-dji:FlightPitchDegree",
            "core": "xmp_bloco_1",
            "label": "Flight Pitch Degree",
            "attribute": "DronePitc",
            "description": "Angulo de pitch da aeronave em graus. [DronePitc]",
        },
        "FlightXSpeed": {
            "normalized": "xmp_bloco_1:drone-dji:FlightXSpeed",
            "core": "xmp_bloco_1",
            "label": "Flight X Speed",
            "attribute": "XSpeed",
            "description": "Velocidade da aeronave no eixo X. [XSpeed]",
        },
        "FlightYSpeed": {
            "normalized": "xmp_bloco_1:drone-dji:FlightYSpeed",
            "core": "xmp_bloco_1",
            "label": "Flight Y Speed",
            "attribute": "YSpeed",
            "description": "Velocidade da aeronave no eixo Y. [YSpeed]",
        },
        "FlightZSpeed": {
            "normalized": "xmp_bloco_1:drone-dji:FlightZSpeed",
            "core": "xmp_bloco_1",
            "label": "Flight Z Speed",
            "attribute": "ZSpeed",
            "description": "Velocidade da aeronave no eixo Z. [ZSpeed]",
        },
        "RtkFlag": {
            "normalized": "xmp_bloco_1:drone-dji:RtkFlag",
            "core": "xmp_bloco_1",
            "label": "RTK Flag",
            "attribute": "RtkFlag",
            "description": "Indicador de qualidade/correcao RTK. [RtkFlag]",
        },
        "RtkStdLon": {
            "normalized": "xmp_bloco_1:drone-dji:RtkStdLon",
            "core": "xmp_bloco_1",
            "label": "RTK Std Lon",
            "attribute": "RtkStdLon",
            "description": "Desvio padrao RTK na longitude. [RtkStdLon]",
        },
        "RtkStdLat": {
            "normalized": "xmp_bloco_1:drone-dji:RtkStdLat",
            "core": "xmp_bloco_1",
            "label": "RTK Std Lat",
            "attribute": "RtkStdLat",
            "description": "Desvio padrao RTK na latitude. [RtkStdLat]",
        },
        "RtkStdHgt": {
            "normalized": "xmp_bloco_1:drone-dji:RtkStdHgt",
            "core": "xmp_bloco_1",
            "label": "RTK Std Hgt",
            "attribute": "RtkStdHgt",
            "description": "Desvio padrao RTK na altitude. [RtkStdHgt]",
        },
        "RtkDiffAge": {
            "normalized": "xmp_bloco_1:drone-dji:RtkDiffAge",
            "core": "xmp_bloco_1",
            "label": "RTK Diff Age",
            "attribute": "RtkDifAge",
            "description": "Tempo desde a ultima correcao RTK. [RtkDifAge]",
        },
        "DewarpFlag": {
            "normalized": "xmp_bloco_1:drone-dji:DewarpFlag",
            "core": "xmp_bloco_1",
            "label": "Dewarp Flag",
            "attribute": "Dewarp",
            "description": "Estado da correcao de distorcao (dewarp). [Dewarp]",
        },
        "UTCAtExposure": {
            "normalized": "xmp_bloco_1:drone-dji:UTCAtExposure",
            "core": "xmp_bloco_1",
            "label": "UTC At Exposure",
            "attribute": "UTCTime",
            "description": "Horario UTC exato do momento da exposicao. [UTCTime]",
        },
        "ShutterCount": {
            "normalized": "xmp_bloco_1:drone-dji:ShutterCount",
            "core": "xmp_bloco_1",
            "label": "Shutter Count",
            "attribute": "ShotCount",
            "description": "Total de disparos acumulados da camera. [ShotCount]",
        },
        "FocusDistance": {
            "normalized": "xmp_bloco_1:drone-dji:FocusDistance",
            "core": "xmp_bloco_1",
            "label": "Focus Distance",
            "attribute": "FocusDist",
            "description": "Distancia de foco usada na captura. [FocusDist]",
        },
        "CameraSerialNumber": {
            "normalized": "xmp_bloco_1:drone-dji:CameraSerialNumber",
            "core": "xmp_bloco_1",
            "label": "Camera Serial Number",
            "attribute": "CameraID",
            "description": "Numero serial da camera. [CameraID]",
        },
        "DroneModel": {
            "normalized": "xmp_bloco_1:drone-dji:DroneModel",
            "core": "xmp_bloco_1",
            "label": "Drone Model",
            "attribute": "DronModel",
            "description": "Modelo da aeronave/drone. [DronModel]",
        },
        "DroneSerialNumber": {
            "normalized": "xmp_bloco_1:drone-dji:DroneSerialNumber",
            "core": "xmp_bloco_1",
            "label": "Drone Serial Number",
            "attribute": "DroneID",
            "description": "Numero serial da aeronave/drone. [DroneID]",
        },
        "CaptureUUID": {
            "normalized": "xmp_bloco_1:drone-dji:CaptureUUID",
            "core": "xmp_bloco_1",
            "label": "Capture UUID",
            "attribute": "CaptureID",
            "description": "Identificador unico do conjunto de captura. [CaptureID]",
        },
        "PictureQuality": {
            "normalized": "xmp_bloco_1:drone-dji:PictureQuality",
            "core": "xmp_bloco_1",
            "label": "Picture Quality",
            "attribute": "ImgQualit",
            "description": "Nivel de qualidade/compressao da imagem. [ImgQualit]",
        },
        "segmentos_total": {
            "normalized": "JPEG:segmentos_total",
            "core": "xmp_bloco_1",
            "label": "Segmentos Total",
            "attribute": "Segments",
            "description": "Quantidade total de segmentos JPEG lidos. [Segments]",
        },
        "SensorTemperature": {
            "normalized": "xmp_bloco_1:drone-dji:SensorTemperature",
            "core": "xmp_bloco_1",
            "label": "Sensor Temperature",
            "attribute": "SensTemp",
            "description": "Temperatura do sensor da camera. [SensTemp]",
        },
        "LRFStatus": {
            "normalized": "xmp_bloco_1:drone-dji:LRFStatus",
            "core": "xmp_bloco_1",
            "label": "LRF Status",
            "attribute": "LRFStatus",
            "description": "Status do laser range finder (LRF). [LRFStatus]",
        },
        "LRFTargetDistance": {
            "normalized": "xmp_bloco_1:drone-dji:LRFTargetDistance",
            "core": "xmp_bloco_1",
            "label": "LRF Target Distance",
            "attribute": "LRFDist",
            "description": "Distancia medida pelo LRF ate o alvo central. [LRFDist]",
        },
        "LRFTargetLon": {
            "normalized": "xmp_bloco_1:drone-dji:LRFTargetLon",
            "core": "xmp_bloco_1",
            "label": "LRF Target Lon",
            "attribute": "LRFLong",
            "description": "Longitude do alvo medida pelo LRF. [LRFLong]",
        },
        "LRFTargetLat": {
            "normalized": "xmp_bloco_1:drone-dji:LRFTargetLat",
            "core": "xmp_bloco_1",
            "label": "LRF Target Lat",
            "attribute": "LRFLati",
            "description": "Latitude do alvo medida pelo LRF. [LRFLati]",
        },
        "LRFTargetAlt": {
            "normalized": "xmp_bloco_1:drone-dji:LRFTargetAlt",
            "core": "xmp_bloco_1",
            "label": "LRF Target Alt",
            "attribute": "LRFY",
            "description": "Altitude relativa do alvo medida pelo LRF. [LRFY]",
        },
        "LRFTargetAbsAlt": {
            "normalized": "xmp_bloco_1:drone-dji:LRFTargetAbsAlt",
            "core": "xmp_bloco_1",
            "label": "LRF Target Abs Alt",
            "attribute": "LrfAbsAlt",
            "description": "Altitude absoluta do alvo medida pelo LRF. [LrfAbsAlt]",
        },
        "WhiteBalanceCCT": {
            "normalized": "xmp_bloco_1:drone-dji:WhiteBalanceCCT",
            "core": "xmp_bloco_1",
            "label": "White Balance CCT",
            "attribute": "WhiteBlc",
            "description": "Temperatura de cor (Kelvin) no balanco de branco. [WhiteBlc]",
        },
        "SensorFPS": {
            "normalized": "xmp_bloco_1:drone-dji:SensorFPS",
            "core": "xmp_bloco_1",
            "label": "Sensor FPS",
            "attribute": "SensorFPS",
            "description": "Taxa de amostragem do sensor em FPS. [SensorFPS]",
        },
        "RecommendedExposureIndex": {
            "normalized": "EXIF:RecommendedExposureIndex",
            "core": "xmp_bloco_1",
            "label": "Recommended Exposure Index",
            "attribute": "REI",
            "description": "Indice de exposicao recomendado (REI). [REI]",
        },
        "LensPosition": {
            "normalized": "xmp_bloco_1:drone-dji:LensPosition",
            "core": "xmp_bloco_1",
            "label": "Lens Position",
            "attribute": "LensPosit",
            "description": "Posicao da lente no momento da captura. [LensPosit]",
        },
        "LensTemperature": {
            "normalized": "xmp_bloco_1:drone-dji:LensTemperature",
            "core": "xmp_bloco_1",
            "label": "Lens Temperature",
            "attribute": "LensTemp",
            "description": "Temperatura da lente no momento da captura. [LensTemp]",
        },
    }

    CUSTOM_FIELDS = {
        "FileType": {
            "normalized": "Custom:FileType",
            "core": "custom",
            "label": "File Type",
            "attribute": "FileType",
            "description": "Tipo/Extensao do arquivo de imagem (ex.: .JPG). [FileType]",
        },
        "dt_full": {
            "normalized": "Custom:dt_full",
            "core": "custom",
            "label": "Date Time Full",
            "attribute": "DateTimeFull",
            "description": "Data/hora compacta no formato YYYYMMDDHHMM. [DateTimeFull]",
        },
        "dt_date": {
            "normalized": "Custom:dt_date",
            "core": "custom",
            "label": "Date Only",
            "attribute": "DateOnly",
            "description": "Data compacta no formato YYYYMMDD. [DateOnly]",
        },
        "dt_time": {
            "normalized": "Custom:dt_time",
            "core": "custom",
            "label": "Time Only",
            "attribute": "TimeOnly",
            "description": "Horario compacto no formato HHMM. [TimeOnly]",
        },
        "FlightNumber": {
            "normalized": "Custom:FlightNumber",
            "core": "custom",
            "label": "Flight Number",
            "attribute": "FlightNum",
            "description": "Numero do voo derivado do MRK (numdovoo). [FlightNum]",
        },
        "FlightName": {
            "normalized": "Custom:FlightName",
            "core": "custom",
            "label": "Flight Name",
            "attribute": "FlightName",
            "description": "Nome do voo derivado do MRK (nomedovoo). [FlightName]",
        },
        "FolderLevel1": {
            "normalized": "Custom:FolderLevel1",
            "core": "custom",
            "label": "Folder Level 1",
            "attribute": "FolderL1",
            "description": "Primeiro nivel de pasta do voo (pasta1). [FolderL1]",
        },
        "FolderLevel2": {
            "normalized": "Custom:FolderLevel2",
            "core": "custom",
            "label": "Folder Level 2",
            "attribute": "FolderL2",
            "description": "Segundo nivel de pasta do voo (pasta2). [FolderL2]",
        },
        "GimbalOffset": {
            "normalized": "xmp_bloco_1:drone-dji:GimbalOffset",
            "core": "custom",
            "label": "Gimbal Offset",
            "attribute": "GimOffset",
            "description": "Deslocamento angular mínimo do gimbal em relação à aeronave em graus (GimbalYawDegree - FlightYawDegree - 180, normalizado para menor ângulo). Valores: 0-180°. Valor referência: <1°. [GimOffset]",
        },
        "3DSpeed": {
            "normalized": "Custom:3DSpeed",
            "core": "custom",
            "label": "3 D Speed",
            "attribute": "3DSpeed",
            "description": "Velocidade total 3D da aeronave em m/s, calculada como sqrt(FlightXSpeed² + FlightYSpeed² + FlightZSpeed²). Valores: 0-50 m/s. Valor referência: <10 m/s para voos estáveis. [3DSpeed]",
        },
        "time_since_previous": {
            "normalized": "Custom:time_since_previous",
            "core": "custom",
            "label": "Time Since Previous",
            "attribute": "TimePrv",
            "description": "Tempo em segundos desde a foto anterior. Valores: 0-120 s. Valor referência: 2-5 s para cadência ideal. [TimePrv]",
        },
        "geodesic_distance_previous": {
            "normalized": "Custom:geodesic_distance_previous",
            "core": "custom",
            "label": "Geodesic Distance Previous",
            "attribute": "GeoDstP",
            "description": "Distância horizontal em metros entre posições GPS consecutivas (fórmula Haversine). Valores: 0-100 m. Valor referência: 20-50 m para sobreposição adequada. [GeoDstP]",
        },
        "distance_3d_previous": {
            "normalized": "Custom:distance_3d_previous",
            "core": "custom",
            "label": "Distance 3 D Previous",
            "attribute": "Dist3DP",
            "description": "Distância 3D em metros entre posições consecutivas (horizontal + altitude). Valores: 0-100 m. Valor referência: 20-50 m. [Dist3DP]",
        },
        "avg_velocity_between_photos": {
            "normalized": "Custom:avg_velocity_between_photos",
            "core": "custom",
            "label": "Avg Velocity Between Photos",
            "attribute": "AvgVelB",
            "description": "Velocidade média em m/s entre fotos consecutivas. Valores: 0-20 m/s. Valor referência: 5-10 m/s. [AvgVelB]",
        },
        "linear_velocity_instant": {
            "normalized": "Custom:linear_velocity_instant",
            "core": "custom",
            "label": "Linear Velocity Instant",
            "attribute": "LinVelI",
            "description": "Velocidade instantânea 3D em m/s. Valores: 0-50 m/s. Valor referência: <10 m/s. [LinVelI]",
        },
        "displacement_direction": {
            "normalized": "Custom:displacement_direction",
            "core": "custom",
            "label": "Displacement Direction",
            "attribute": "DirDispl",
            "description": "Azimute do deslocamento em graus (0=Norte). Valores: 0-360°. Valor referência: varia por missão. [DirDispl]",
        },
        "incidence_angle": {
            "normalized": "Custom:incidence_angle",
            "core": "custom",
            "label": "Incidence Angle",
            "attribute": "IncAngle",
            "description": "Ângulo de incidência em graus (ângulo entre câmera e vertical). Valores: 0-180°. Valor referência: <5° para nadir. [IncAngle]",
        },
        "estimated_coverage": {
            "normalized": "Custom:estimated_coverage",
            "core": "custom",
            "label": "Estimated Coverage",
            "attribute": "EstCover",
            "description": "Tupla (largura, altura) em metros da cobertura estimada no solo. Valores: (0-200, 0-150) m. Valor referência: depende altitude. [EstCover]",
        },
        "predicted_overlap": {
            "normalized": "Custom:predicted_overlap",
            "core": "custom",
            "label": "Predicted Overlap",
            "attribute": "PredOver",
            "description": "Percentual de sobreposição longitudinal com foto anterior. Valores: 0-100%. Valor referência: >60%. [PredOver]",
        },
        "rtk_effective_precision": {
            "normalized": "Custom:rtk_effective_precision",
            "core": "custom",
            "label": "RTK Effective Precision",
            "attribute": "RTKPrec",
            "description": "Classificação textual da precisão RTK. Valores: Alta, Média, Baixa, Sem RTK. Valor referência: Alta. [RTKPrec]",
        },
        "is_ideal_overlap": {
            "normalized": "Custom:is_ideal_overlap",
            "core": "custom",
            "label": "Is Ideal Overlap",
            "attribute": "IdealOvl",
            "description": "Booleano indicando se sobreposição >=60%. Valores: True/False. Valor referência: True. [IdealOvl]",
        },
        "abrupt_change_flag": {
            "normalized": "Custom:abrupt_change_flag",
            "core": "custom",
            "label": "Abrupt Change Flag",
            "attribute": "AbrChgF",
            "description": "Flag de mudança brusca (tempo ou distância >2x mediana). Valores: True/False. Valor referência: False. [AbrChgF]",
        },
        "gimbal_angular_velocity": {
            "normalized": "Custom:gimbal_angular_velocity",
            "core": "custom",
            "label": "Gimbal Angular Velocity",
            "attribute": "GimAngV",
            "description": "Variação angular do gimbal em °/s. Valores: 0-100 °/s. Valor referência: <1 °/s. [GimAngV]",
        },
        "orthorectification_potential": {
            "normalized": "Custom:orthorectification_potential",
            "core": "custom",
            "label": "Orthorectification Potential",
            "attribute": "OrtoPot",
            "description": "Score de potencial para ortorretificação (0-100). Valores: 0-100. Valor referência: >80. [OrtoPot]",
        },
        "shutter_life_pct": {
            "normalized": "Custom:shutter_life_pct",
            "core": "custom",
            "label": "Shutter Life Pct",
            "attribute": "ShutPct",
            "description": "% de vida útil do obturador. Valores: 0-100%. Valor referência: <50%. [ShutPct]",
        },
        "ground_sample_distance_cm": {
            "normalized": "Custom:ground_sample_distance_cm",
            "core": "custom",
            "label": "Ground Sample Distance Cm",
            "attribute": "GsdCmPx",
            "description": "GSD em cm/pixel. Valores: 0-10 cm. Valor referência: <2 cm. [GsdCmPx]",
        },
        "total_heat_index": {
            "normalized": "Custom:total_heat_index",
            "core": "custom",
            "label": "Total Heat Index",
            "attribute": "HeatIdx",
            "description": "Índice térmico médio em °C. Valores: 20-60 °C. Valor referência: <40 °C. [HeatIdx]",
        },
        "speed_3d_kmh": {
            "normalized": "Custom:speed_3d_kmh",
            "core": "custom",
            "label": "Speed 3 D Kmh",
            "attribute": "SpdKmH",
            "description": "Velocidade 3D do drone em km/h. Valores: 0-180 km/h. Valor referência: <36 km/h. [SpdKmH]",
        },
        "yaw_alignment_error": {
            "normalized": "Custom:yaw_alignment_error",
            "core": "custom",
            "label": "Yaw Alignment Error",
            "attribute": "YawErr",
            "description": "Erro de alinhamento yaw em graus. Valores: 0-180°. Valor referência: <5°. [YawErr]",
        },
        "motion_blur_risk": {
            "normalized": "Custom:motion_blur_risk",
            "core": "custom",
            "label": "Motion Blur Risk",
            "attribute": "BlurRisk",
            "description": "Risco de motion blur em pixels. Valores: 0-5. Valor referência: <0.5. [BlurRisk]",
        },
        "exposure_value_ev": {
            "normalized": "Custom:exposure_value_ev",
            "core": "custom",
            "label": "Exposure Value EV",
            "attribute": "EV",
            "description": "Valor de exposição EV. Valores: 8-16. Valor referência: 12-14. [EV]",
        },
        "light_source_classification": {
            "normalized": "Custom:light_source_classification",
            "core": "custom",
            "label": "Light Source Classification",
            "attribute": "LSrcClass",
            "description": "Classificação textual da fonte de luz EXIF. Valores: Daylight, Fluorescent, etc. Valor referência: Daylight. [LSrcClass]",
        },
        "light_consistency": {
            "normalized": "Custom:light_consistency",
            "core": "custom",
            "label": "Light Consistency",
            "attribute": "LightCons",
            "description": "Consistência entre LightSource e CCT. Valores: Consistent, Inconsistent, Unknown. Valor referência: Consistent. [LightCons]",
        },
        "vertical_stability": {
            "normalized": "Custom:vertical_stability",
            "core": "custom",
            "label": "Vertical Stability",
            "attribute": "VertStb",
            "description": "Variação vertical em metros. Valores: 0-10 m. Valor referência: <1 m. [VertStb]",
        },
        "trajectory_smoothness": {
            "normalized": "Custom:trajectory_smoothness",
            "core": "custom",
            "label": "Trajectory Smoothness",
            "attribute": "TrajSmt",
            "description": "Diferença angular de direção em graus. Valores: 0-180°. Valor referência: <10°. [TrajSmt]",
        },
        "speed_variation_index": {
            "normalized": "Custom:speed_variation_index",
            "core": "custom",
            "label": "Speed Variation Index",
            "attribute": "SpdVar",
            "description": "Índice de variação de velocidade (coeficiente de variação). Valores: 0-1. Valor referência: <0.1. [SpdVar]",
        },
        "rtk_stability_score": {
            "normalized": "Custom:rtk_stability_score",
            "core": "custom",
            "label": "RTK Stability Score",
            "attribute": "RtkStab",
            "description": "Score de estabilidade RTK (0-100). Valores: 0-100. Valor referência: >90. [RtkStab]",
        },
        "capture_efficiency": {
            "normalized": "Custom:capture_efficiency",
            "core": "custom",
            "label": "Capture Efficiency",
            "attribute": "CapEff",
            "description": "Eficiência de captura (distância/cobertura). Valores: 0-1. Valor referência: 0.5-0.8. [CapEff]",
        },
        "photogrammetry_quality_index": {
            "normalized": "Custom:photogrammetry_quality_index",
            "core": "custom",
            "label": "Photogrammetry Quality Index",
            "attribute": "PQI",
            "description": "Índice de qualidade fotogramétrica (0-100). Valores: 0-100. Valor referência: >80. [PQI]",
        },
        "strip_id": {
            "normalized": "Custom:strip_id",
            "core": "custom",
            "label": "Strip ID",
            "attribute": "StripID",
            "description": "ID da faixa de voo. Valores: 1+. Valor referência: incremental. [StripID]",
        },
    }

    MRK_FIELDS = {
        "foto": {
            "normalized": "MRK:foto",
            "core": "mrk",
            "label": "Photo Number",
            "attribute": "PhotoNum",
            "description": "Numero sequencial da foto vindo do MRK. [PhotoNum]",
        },
        "lat": {
            "normalized": "MRK:lat",
            "core": "mrk",
            "label": "Latitude",
            "attribute": "Latitude",
            "description": "Latitude extraida do arquivo MRK. [Latitude]",
        },
        "lon": {
            "normalized": "MRK:lon",
            "core": "mrk",
            "label": "Longitude",
            "attribute": "Longitude",
            "description": "Longitude extraida do arquivo MRK. [Longitude]",
        },
        "alt": {
            "normalized": "MRK:alt",
            "core": "mrk",
            "label": "Altitude",
            "attribute": "Altitude",
            "description": "Altitude extraida do arquivo MRK. [Altitude]",
        },
        "data_name": {
            "normalized": "MRK:data_name",
            "core": "mrk",
            "label": "Date Name",
            "attribute": "DateName",
            "description": "Data identificada a partir do nome do MRK. [DateName]",
        },
        "mrk_file": {
            "normalized": "MRK:mrk_file",
            "core": "mrk",
            "label": "MRK File",
            "attribute": "MrkFile",
            "description": "Nome do arquivo MRK de origem. [MrkFile]",
        },
        "mrk_path": {
            "normalized": "MRK:mrk_path",
            "core": "mrk",
            "label": "MRK Path",
            "attribute": "MrkPath",
            "description": "Caminho completo do arquivo MRK de origem. [MrkPath]",
        },
        "mrk_folder": {
            "normalized": "MRK:mrk_folder",
            "core": "mrk",
            "label": "MRK Folder",
            "attribute": "MrkFolder",
            "description": "Pasta absoluta de origem do ponto MRK. [MrkFolder]",
        },
        "numdovoo": {
            "normalized": "MRK:numdovoo",
            "core": "mrk",
            "label": "Flight Number (Legacy)",
            "attribute": "NumDoVoo",
            "description": "Numero do voo no padrao legado MRK. [NumDoVoo]",
        },
        "nomedovoo": {
            "normalized": "MRK:nomedovoo",
            "core": "mrk",
            "label": "Flight Name (Legacy)",
            "attribute": "NomeDoVoo",
            "description": "Nome do voo no padrao legado MRK. [NomeDoVoo]",
        },
        "pasta1": {
            "normalized": "MRK:pasta1",
            "core": "mrk",
            "label": "Folder 1 (Legacy)",
            "attribute": "Pasta1",
            "description": "Primeiro nivel de pasta no padrao legado MRK. [Pasta1]",
        },
        "pasta2": {
            "normalized": "MRK:pasta2",
            "core": "mrk",
            "label": "Folder 2 (Legacy)",
            "attribute": "Pasta2",
            "description": "Segundo nivel de pasta no padrao legado MRK. [Pasta2]",
        },
    }

    LIGHT_SOURCE_VALUES = {
        0: {
            "value": "Unknown",
            "description": "Fonte de luz desconhecida ou não especificada. Este valor é frequentemente usado quando o dado não foi registrado ou é inválido.",
        },
        1: {
            "value": "Daylight",
            "description": "Luz do dia, referente à iluminação solar natural. Corresponde ao balanço de branco para condições diurnas, com temperatura de cor por volta de 5200K-6500K.",
        },
        2: {
            "value": "Fluorescent",
            "description": "Iluminação fluorescente, típica de lâmpadas de luz do dia. Apresenta uma temperatura de cor variando geralmente entre 3000K e 6500K, dependendo do tipo da lâmpada.",
        },
        3: {
            "value": "Tungsten",
            "description": "Iluminação de tungstênio (lâmpada incandescente), com tom amarelado característico. A temperatura de cor normalmente fica na faixa dos 2800K a 3200K.",
        },
        4: {
            "value": "Flash",
            "description": "Iluminação fornecida pelo flash da câmera. Este valor é registrado quando o flash é disparado e atua como fonte de luz principal ou de preenchimento.",
        },
        9: {
            "value": "Fine Weather",
            "description": "Tempo claro, condição de luz do dia sem nuvens. Representa uma iluminação de alta intensidade e com temperatura de cor bem definida.",
        },
        10: {
            "value": "Cloudy Weather",
            "description": "Tempo nublado, onde a luz do sol é difusa devido à cobertura de nuvens. Geralmente resulta em uma temperatura de cor mais alta, por volta de 6500K-7500K.",
        },
        11: {
            "value": "Shade",
            "description": "Área de sombra, onde a iluminação solar é bloqueada por obstáculos. A luz refletida do céu tende a ser mais azulada, com temperatura de cor superior a 7000K.",
        },
        12: {
            "value": "Daylight Fluorescent",
            "description": "Luz fluorescente do tipo Daylight, que emula a cor da luz do dia. Apresenta uma temperatura de cor típica entre 5700K e 7100K, indicada para ambientes internos.",
        },
        13: {
            "value": "Day White Fluorescent",
            "description": "Luz fluorescente branca diurna, com uma tonalidade neutra. A temperatura de cor dessa fonte varia de 4600K a 5400K.",
        },
        14: {
            "value": "Cool White Fluorescent",
            "description": "Luz fluorescente branca fria, com uma aparência mais azulada. Este tipo de iluminação opera com uma temperatura de cor na faixa de 3800K a 4500K.",
        },
        15: {
            "value": "White Fluorescent",
            "description": "Luz fluorescente branca, oferecendo um equilíbrio entre tons quentes e frios. Sua temperatura de cor geralmente está entre 3250K e 3800K.",
        },
        16: {
            "value": "Warm White Fluorescent",
            "description": "Luz fluorescente branca quente, com tonalidade mais amarelada. É comum em lâmpadas do tipo WW, operando com temperatura de cor de 2600K a 3250K.",
        },
        17: {
            "value": "Standard Light A",
            "description": "Luz padrão do tipo A, que representa uma fonte de luz incandescente. É utilizada como referência para simular iluminação residencial comum.",
        },
        18: {
            "value": "Standard Light B",
            "description": "Luz padrão do tipo B, usada para representar a luz solar direta. Faz parte das referências padronizadas para avaliação de reprodução de cores.",
        },
        19: {
            "value": "Standard Light C",
            "description": "Luz padrão do tipo C, que simula a luz do dia média. É outra referência importante em estudos de temperatura de cor e fidelidade tonal.",
        },
        20: {
            "value": "D55",
            "description": "Iluminante D55, com temperatura de cor de 5500 Kelvin. É utilizado como padrão na indústria gráfica e fotográfica para condições de luz do dia.",
        },
        21: {
            "value": "D65",
            "description": "Iluminante D65, com temperatura de cor de 6500 Kelvin. Representa a luz do dia média na Europa e é o padrão mais comum para monitores e softwares de edição.",
        },
        22: {
            "value": "D75",
            "description": "Iluminante D75, com temperatura de cor de 7500 Kelvin. Simula uma luz do dia com maior componente azul, típica de céus muito claros.",
        },
        23: {
            "value": "D50",
            "description": "Iluminante D50, com temperatura de cor de 5000 Kelvin. É um padrão amplamente utilizado nas artes gráficas e na indústria de impressão.",
        },
        24: {
            "value": "ISO Studio Tungsten",
            "description": "Iluminação de tungstênio para estúdio, conforme padrão ISO. Utilizada em ambientes profissionais para obter uma luz contínua e de alta intensidade.",
        },
        255: {
            "value": "Other Light Source",
            "description": "Outra fonte de luz não listada nas categorias padrão do EXIF. Este valor é utilizado para indicar uma condição de iluminação fora do comum.",
        },
    }
